INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Berlin', 'Paris', '2024-10-12', 1412, 114, 'Business', '3 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Tokyo', 'Berlin', '2024-10-08', 1155, 292, 'First', '2 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Sydney', 'Paris', '2024-09-27', 329, 55, 'Business', '3 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Berlin', 'Tokyo', '2024-09-19', 1343, 252, 'Business', 'None');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Los Angeles', 'New York', '2024-10-15', 621, 222, 'First', '2 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Paris', 'Sydney', '2024-10-10', 727, 68, 'First', '3 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Tokyo', 'Sydney', '2024-10-07', 892, 277, 'Business', '1 Bag');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Sydney', 'Rome', '2024-09-13', 977, 89, 'First', '2 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('New York', 'Rome', '2024-10-31', 1396, 254, 'First', '2 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Sydney', 'New York', '2024-09-30', 596, 256, 'Economy', '1 Bag');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Tokyo', 'New York', '2024-09-19', 285, 270, 'Business', '3 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Berlin', 'Sydney', '2024-10-04', 1200, 148, 'Economy', '2 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('London', 'Tokyo', '2024-10-07', 864, 170, 'First', '3 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('London', 'Sydney', '2024-10-31', 765, 95, 'First', '3 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Los Angeles', 'Rome', '2024-09-23', 1462, 276, 'Economy', '3 Bags');
INSERT INTO FLIGHT (origin, destination, date, price, max_Pax, clase, baggage) VALUES ('Berlin', 'Tokyo', '2024-10-07', 922, 244, 'Business', '2 Bags');
